apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "wordpress-dump-cronjob.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-cronjob.name" . }}
    chart: {{ template "wordpress-dump-cronjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  {{- with .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app: {{ template "wordpress-dump-cronjob.name" . }}
        release: {{ .Release.Name }}
    spec:
      template:
        metadata:
          labels:
            app: {{ template "wordpress-dump-cronjob.name" . }}
            release: {{ .Release.Name }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: {{ template "wordpress-dump-cronjob.image" . }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["bash",  "dump.sh"]
            env:
              - name: APP_NAME
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: app
              - name: DB_NAME
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: db
              - name: DB_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: dbhost
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: dbuser
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: dbpass
              - name: DROPBOX_AUTH
                valueFrom:
                  secretKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}-dropbox
                    key: authentication
              - name: ALL_DATABASES
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: all_databases
              - name: BACKUP_DIR
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "wordpress-dump-cronjob.fullname" . }}
                    key: backup-dir
            volumeMounts:
              - name: wordpress-dump
                mountPath: /dump
              - name: wordpress-operational
                mountPath: /data
          imagePullSecrets:
            - name: {{ template "wordpress-dump-cronjob.fullname" . }}-tc
          volumes:
            - name: wordpress-dump
              persistentVolumeClaim:
                claimName: {{ template "wordpress-dump-cronjob.fullname" . }}
            - name: wordpress-operational
              persistentVolumeClaim:
                claimName:  {{ .Values.wordpress.persistent.readwritemany.volumeclaim }}
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wordpress-dump-cronjob.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-cronjob.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
{{- end }}