apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ul-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ul-frontend.name" . }}
    helm.sh/chart: {{ include "ul-frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ul-frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ul-frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ 'bash','-c','bash kubernetes/add_environment_variables.tsk && nginx -g daemon off']
          env:
          - name: VOTE_API_ADDRESS
            value: 'https://{{ .Values.vote.url }}'
          - name: VOTE_API_PORT
            value: '{{ .Values.vote.port }}'
          ports:
          - containerPort: {{ .Values.deployment.port }}
      imagePullSecrets:
        - name: {{ .Values.registry.secret }}
