{{- if and .Values.image .Values.image.password }}
apiVersion: v1
metadata:
  name: {{ template "wordpress-dump-job.fullname" . }}-{{ .Values.image.credentailsname }}
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7IlVzZXJuYW1lIjoicnViZW4tZW5hYmxlIiwiUGFzc3dvcmQiOiI5LXpNVmRRVTJYQUg0NnZpNTZFOCIsIkVtYWlsIjoicnViZW5Abi1hYmxlLmNvbnN1bHRpbmcifX19
kind: Secret
metadata:
  name: {{ template "wordpress-dump-job.fullname" . }}-tc
type: kubernetes.io/dockerconfigjson