apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "wordpress-dump-job.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-job.name" . }}
    chart: {{ template "wordpress-dump-job.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "wordpress-dump-job.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        #image: {{ template "wordpress-dump-job.image" . }}
        image: 'registry.gitlab.com/ruben-enable/wordpress-dump-job:job'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bash",  "dump.sh"]
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: app
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: db
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: dbhost
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: dbpass
          - name: DROPBOX_AUTH
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}-dropbox
                key: authentication
          - name: ALL_DATABASES
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: all_databases
          - name: BACKUP_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-job.fullname" . }}
                key: backup-dir
        volumeMounts:
          - name: wordpress-dump
            mountPath: /dump
          - name: wordpress-operational
            mountPath: /data
      imagePullSecrets:
        - name: {{ template "wordpress-dump-job.fullname" . }}-tc
      volumes:
        - name: wordpress-dump
          persistentVolumeClaim:
            claimName: {{ template "wordpress-dump-job.fullname" . }}
        - name: wordpress-operational
          persistentVolumeClaim:
            claimName:  {{ .Values.wordpress.persistent.readwritemany.volumeclaim }}
      restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wordpress-dump-job.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-job.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
{{- end }}