apiVersion: v1
appVersion: "1.0"
description: "N-Able Training: Subject Single Sign On - Frontoffice Application. Example of how to add RBAC to applictions using OAuth2 SSO."
name: sso-app-frontend
version: 0.1.0
