{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $ingress.host }}-crt
spec:
  secretName: {{ $ingress.host }}-tls
  dnsNames:
    - {{ $ingress.host }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ $ingress.host }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  {{- end }}