apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-vote.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "voting-vote.name" . }}
    helm.sh/chart: {{ include "voting-vote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voting-vote.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voting-vote.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DATABASE_HOST
            value: '{{ .Values.database.service }}'
          - name: DATABASE_PORT
            value: '{{ .Values.database.port }}'
          - name: DATABASE_NAME
            value: '{{ .Values.database.name }}'
          - name: QUEUE_HOST
            value: '{{ .Values.queue.service }}'
          - name: QUEUE_PORT
            value: '{{ .Values.queue.port }}'
          - name: REPORTS_SERVICE
            value: '{{ .Values.reports.service }}'
          - name: REPORTS_PORT
            value: '{{ .Values.reports.port }}'
          - name: VOTING_SERVICE
            value: '{{ .Values.voting.service }}'
          - name: VOTING_PORT
            value: '{{ .Values.voting.port }}'
          - name: VOTE_SERVICE
            value: '{{ .Values.vote.service }}'
          - name: VOTE_PORT
            value: '{{ .Values.vote.port }}'
          ports:
          - containerPort: {{ .Values.deployment.port }}
      imagePullSecrets:
        - name: {{ .Values.registry.secret }}