apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sso-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sso-backend.name" . }}
    helm.sh/chart: {{ include "sso-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sso-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sso-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KEYCLOAK_URL
            value: https://{{ .Values.ssoBackendContainer.idserviceUrl }}/auth
          ports:
          - name: http
            containerPort: {{ .Values.ssoBackendContainer.port }}
          readinessProbe:
            httpGet:
              path: /public
              port: {{ .Values.ssoBackendContainer.port }}