{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.host }}-rules
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
{{- with $ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "sso-backend.name" . }}
    helm.sh/chart: {{ include "sso-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
      - {{ $ingress.host }}
      secretName: {{ $ingress.host }}-tls
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "sso-backend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}