#bla
nameOverride: ""
fullnameOverride: ""

wordpress:
  #sitename is essential for keeping imports apart in the backup directory
  sitename: "Participant-One-Wordpress"
  persistent:
    readwritemany:
      volumeclaim: "test-wordpress-bla-wp-wordpress"
  database:
    service: "test-wordpress-bla-db-my-0.test-wordpress-bla-db-my"
    user: "root"
    password: "W9B107RTBy0N8shMHcMZI6kw4ZIzMotbuh9jX3xIxlG4mO1pnEtYUT2CH4sJqx7609l0FY0vsfzlK96ohgB7SVTr3eU1FhGMAYej"
    name: "6U7m21L5LOu9W3502ojWP8TWFitwZDna20aL43ci"

backup:
  #optional: "", true, false
  all_databases: "false"
  dir: "participant-one-wordpress"
  restore_number: 0

image:
  registry: registry.gitlab.com
  repository: wordpress-import-job
  tag: pod
  credentailsname: gitlabcredentials
  username: "ruben-enable"
  password: "rGfe5ZRTAFMoaclHi3LBTJ@!SQ&u*POl2kS9&2QBr!zccIoyf4xyoY1^ca4WwPmlmB^VIICok93KLeg%dbMrglGlMXE0lSGIGYXk"
  pullPolicy: Always

persistence:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: "ls-10g"