apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-requirements.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-db
    helm.sh/chart: {{ include "voting-requirements.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.databaseService.type }}
  ports:
    - port: {{ .Values.databaseService.port }}
      targetPort: {{ .Values.databaseService.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/app: database
    app.kubernetes.io/brand: mongodb
