apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-requirements.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-db
    helm.sh/chart: {{ include "voting-requirements.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/app: database
    app.kubernetes.io/brand: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/app: database
      app.kubernetes.io/brand: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/app: database
        app.kubernetes.io/brand: mongodb
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.databaseImage.repository }}:{{ .Values.databaseImage.tag }}"
          imagePullPolicy: {{ .Values.databaseImage.pullPolicy }}
          ports:
          -  containerPort: {{ .Values.databaseDeployment.containerPort }}
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
