apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-requirements.fullname" . }}-queue
  labels:
    app.kubernetes.io/name: {{ include "voting-requirements.name" . }}-queue
    helm.sh/chart: {{ include "voting-requirements.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.queueService.type }}
  ports:
    - port: {{ .Values.queueService.port }}
      targetPort: {{ .Values.queueService.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "voting-requirements.fullname" . }}-queue
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/app: queue
    app.kubernetes.io/brand: redis
