{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $ingress.host }}-rules
  annotations:
    kubernetes.io/tls-acme: "true"
{{- with $ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "clientip.name" . }}
    helm.sh/chart: {{ include "clientip.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  tls:
    - hosts: 
      - {{ $ingress.host }}
      secretName: {{ $ingress.host }}-tls
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path }}
            backend:
              serviceName: {{ include "clientip.fullname" . }}
              servicePort: {{ .Values.service.port }}
  {{- end }}