apiVersion: v1
data:
  dbuser: {{ .Values.wordpress.database.user | b64enc | quote }}
  dbpass: {{ .Values.wordpress.database.password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "wordpress-dump-pod.fullname" . }}
type: Opaque
