apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress-dump-pod.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-pod.name" . }}
    chart: {{ template "wordpress-dump-pod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wordpress-dump-pod.name" . }}
      chart: {{ template "wordpress-dump-pod.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: {{ template "wordpress-dump-pod.name" . }}
        chart: {{ template "wordpress-dump-pod.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "wordpress-dump-pod.image" . }}
        image: 'registry.gitlab.com/ruben-enable/wordpress-dump-job:pod'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sleep", "36000"]
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: app
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: db
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: dbhost
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: dbpass
          - name: DROPBOX_AUTH
            valueFrom:
              secretKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}-dropbox
                key: authentication
          - name: ALL_DATABASES
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: all_databases
          - name: BACKUP_DIR
            valueFrom:
              configMapKeyRef:
                name: {{ template "wordpress-dump-pod.fullname" . }}
                key: backup-dir
        volumeMounts:
          - name: wordpress-dump
            mountPath: /dump
          - name: wordpress-operational
            mountPath: /data
      imagePullSecrets:
        - name: {{ template "wordpress-dump-pod.fullname" . }}-tc
      volumes:
        - name: wordpress-dump
          persistentVolumeClaim:
            claimName: {{ template "wordpress-dump-pod.fullname" . }}
        - name: wordpress-operational
          persistentVolumeClaim:
            claimName:  {{ .Values.wordpress.persistent.readwritemany.volumeclaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wordpress-dump-pod.fullname" . }}
  labels:
    app: {{ template "wordpress-dump-pod.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
{{- end }}