apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-world-secret.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-world-secret.name" . }}
    helm.sh/chart: {{ include "hello-world-secret.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  helloworld: {{ .Values.app.content | b64enc | quote }}