apiVersion: v1
data:
  app: {{ .Values.wordpress.sitename }}
  dbhost: {{ .Values.wordpress.database.service }}
  db: {{ .Values.wordpress.database.name }}
  all_databases: {{ .Values.backup.all_databases | quote }}
  restore_number: {{ .Values.backup.restore_number  | quote  }}
  backup-dir: {{ .Values.backup.dir | quote }}
kind: ConfigMap
metadata:
  name: {{ template "wordpress-import-job.fullname" . }}
